### ISSUE TITLE
a new orm 

### ISSUE THREAD

**Issue by zhajingzhaxi** [nicoburns/blessed-rs#113]
a great ORM lib is rbatis , this is repo  :  https://github.com/rbatis/rbatis

**Comment by djc** [comment]
Looks like rbatis is getting about 15k recent downloads per crates.io, whereas something like sqlx is getting 2.3M. As such, I don't think rbatis has crossed the threshold to being "blessed" by the Rust ecosystem.

**Comment by zhajingzhaxi** [comment]
> Looks like rbatis is getting about 15k recent downloads per crates.io, whereas something like sqlx is getting 2.3M. As such, I don't think rbatis has crossed the threshold to being "blessed" by the Rust ecosystem.


**This is a fact that the monthly downloads of rbatis are not dazzling enough compared to other frameworks**
