### ISSUE TITLE
Add zerocopy to Safe type casts

### ISSUE THREAD

**Issue by russellbanks** [nicoburns/blessed-rs#114]
[Zerocopy](https://github.com/google/zerocopy) is an alternative to bytemuck that has similar popularity and I believe is worth adding.

While bytemuck has ~3x more all-time downloads, zerocopy, by both crates.io and lib.rs metrics, is currently getting more monthly downloads. After trying both crates myself, I can't necessarily recommend one over the other; they both achieved the exact same thing. I personally landed with zerocopy but that was mostly down to it having more recent downloads, being under Google, and having a roadmap for future improvements.

**Comment by djc** [comment]
Yes, this seems reasonable to me. Would you be able to submit a PR?
