### ISSUE TITLE
Notify and watchexec

### ISSUE THREAD

**Issue by passcod** [nicoburns/blessed-rs#13]
Watchexec (the library) is extremely focused on, like, making watch tools. It's only used by a few things, because it has that very particular focus. Notify is the general purpose filesystem watching library. That's the part that's used by like, RA and mdBook and alacritty and all that.

**Comment by nicoburns** [comment]
Yes, I hadn't realised this when I recommended `watchexec` here. `notify` has also since released its 5.0 version. I've updated the recommendation to `notify`.

**Comment by solomatov** [comment]
@passcod, @nicoburns  Is it possible to keep watchexec as an option?

Concerning, why watchexec might be better.  Notify has pretty unusual license (CC0+ Artistic).  Watchexec has Apache 2.0.
