### ISSUE TITLE
rustix

### ISSUE THREAD

**Issue by joshka** [nicoburns/blessed-rs#135]
Rustix (200M downloads) is a memory safe and I/O safe wrapper of many posix / unix / linux calls, with more idiomatic rust like bindings for errors and such. It can be replace usages of libc, nix, etc.

I'd suggest adding this in the system section, but not quite sure whether it's best to put it next to libc or nix. There's some overlap in both (and for sockets there's even overlap in the windows side of things).

**Comment by hniksic** [comment]
rustix seems like an "obvious" alternative to nix. Another feature I'd mention is that it seems more efficient by default, as it compiles into Rust-only code that issues syscalls directly without the overhead of libc.

**Comment by nicoburns** [comment]
I feel like it probably ought to go next to (above) nix?

**Comment by hniksic** [comment]
>I feel like it probably ought to go next to (above) nix?

I concur. The two appear to be direct competitors.
