### ISSUE TITLE
surf isn't getting much maintenance

### ISSUE THREAD

**Issue by djc** [nicoburns/blessed-rs#17]
I think the mention of surf should probably come with a caveat, at least:

https://github.com/http-rs/surf/issues/352

For one thing, the latest release of surf (and current Git) still depend on a rustls version from over 2 years ago (2 semver-incompatible versions ago).

**Comment by nicoburns** [comment]
Ah, well spotted. For a few sections with a lot of recommendations I'm planning on hiding some of the listed options behind a HTML details element labelled "see also". I'll add surf to the list of crates to move to this section once it's implemented.

Longer term, I want to pull in the release history and other metadata from crates.io, but I don't want to do this manually, so this will require a bunch of infrastructure setup.

**Comment by nicoburns** [comment]
> For a few sections with a lot of recommendations I'm planning on hiding some of the listed options behind a HTML details element labelled "see also"

This is now implemented. Surf is hidden in a collapsible "See also" section, and I've added a note that it's badly maintained.
