### ISSUE TITLE
Consider mentioning indicatif

### ISSUE THREAD

**Issue by djc** [nicoburns/blessed-rs#18]
(Full disclosure, I am a maintainer for indicatif.)

I think indicatif is probably the de facto standard progress bar library for CLIs, might make sense to mention in the CLI section?

**Comment by nicoburns** [comment]
I haven't used this library myself, but this seems like a useful library and I'm willing to take your word on this being the standard (I also did a quick check on lib.rs, and this seems to be backed up by download counts). I'll add `indicatif` to the list :)
