### ISSUE TITLE
Crate suggestion: `getargs`

### ISSUE THREAD

**Issue by LoganDark** [nicoburns/blessed-rs#25]
Since `lexopt` and `pico-args` are mentioned in the argument parser section, I would like to propose [`getargs`](https://docs.rs/getargs), which I significantly revamped a while ago. (it also works quite well with [`argv`](https://docs.rs/argv))

It is still a minimal argument parser, as opposed to the huge framework that is `clap`, but it is [fairly competitive in benchmarks](https://github.com/j-tai/getargs/tree/master/bench) and also [somewhat pedantic about correctness](https://github.com/j-tai/getargs/blob/465398243dcd78352315e607bd1997dace4a80c4/src/lib.rs#L637-L641). It also has a decent API as far as I can tell, though it is still iterator-based.

It was not accepted into `argparse-benchmarks-rs` due to the low number of downloads that it has. But the purpose of this website is to raise awareness, yes? :D

**Comment by nicoburns** [comment]
> But the purpose of this website is to raise awareness, yes? :D

The purpose of this website is to raise awareness. But it's really for crates that already have wide adoption within the Rust community, to make newcomers aware of them. So unfortunately I don't think your crate will be suitable for inclusion at this time. I'd suggest posting to reddit to see if you get any interest there.

**Comment by LoganDark** [comment]
> it's really for crates that already have wide adoption within the Rust community, to make newcomers aware of them

Thanks, that's all I needed to know.
