### ISSUE TITLE
Potentially add a tooling section

### ISSUE THREAD

**Issue by LovecraftianHorror** [nicoburns/blessed-rs#26]
Not sure if it's outside the scope of this website, but there are some useful external tools like

- [`cargo-nextest`](https://lib.rs/crates/cargo-nextest) - [\[website\]](https://nexte.st)
- [`cross`](https://lib.rs/crates/cross)

**Comment by epage** [comment]
I'd add "release automation".  I list several tools in this space [on cargo release's README](https://github.com/crate-ci/cargo-release#related-tools)

**Comment by epage** [comment]
Maybe also `cargo expand` and either `cargo bloat` or `cargo llvm-lines`.

Probably `cargo-edit` as well though `cargo rm` will be in 1.66, there is still `cargo upgrade`.

**Comment by nicoburns** [comment]
Tooling section added. Leaving this issue open for people to add more tool suggestions.

**Comment by epage** [comment]
Thanks!

In looking at it, the docs.rs links seems less useful.

**Comment by pacak** [comment]
`cargo-show-asm` might be useful somewhere around "Performance" part of the tooling section.

**Comment by nicoburns** [comment]
> I would probably not mention cargo-outdated, which has limited utility once you use cargo upgrade

My workflow is similar to pacak's: I upgrade semver compatible versions using a simple command (`cargo update` can do this natively: no need for a separate tool). For major/minor changes I usually want a list of available versions which I can selectively upgrade. I want to upgrade a single library at a time, fix any breakage, then do the next one. For this I need a list of available updates. A command that just upgrades everything isn't very useful (although a command that upgraded a single library to the latest version would be).

**Comment by epage** [comment]
`cargo upgrade --dry-run` will report a report similar to `cargo outdated`.  We are wanting to settle on a design to stablize in `cargo` and figured the table would be directly helpful and could allow reducing the need for extra commands (similarly, `cargo add` can act as a minimal feature editor).

>  A command that just upgrades everything isn't very useful (although a command that upgraded a single library to the latest version would be).

`cargo upgrade` can do that with `cargo upgrade --package clap` (or `cargo upgrade -p clap` for short) which works well when combined with `--dry-run` for seeing what upgrade options are available.  I should check with the cargo team if there is a reason against adding the common dry-run short of `-n` to existing cargo commands which would make more more comfortable adding it to `cargo upgrade`.

**Comment by pacak** [comment]
> The current version does actually offer options for this -- I use `cargo upgrade --compatible=ignore --incompatible=allow`, for example.

New behavior seems better, but it's about 5 times slower compared `cargo upgrades` - 1 vs 5 seconds.

The way it outputs things though is still worse compared to `cargo upgrades`:
- things are going to `stderr` - a surprising behavior when you have to redirect the output or use it with `less`
- things are formatted in blocks with aligned columns which looks neat if you have only one package but is just a visual mess when you have a bunch of crates in a workspace
- uses colors in not a good way with no obvious way to disable them
- summary at the end contains "unchanged" crates - in my case that's _a lot_ of crates - not very useful, plus it includes crates from the workspace itself which is even more strange. This final blob of text forces you to use `less`/redirect...

**Comment by pacak** [comment]
> mind providing that feedback on

Sure. Is there a place on github with this merge request?

**Comment by epage** [comment]
The above internals thread that I linked is where we are collecting feedback and discussing the design on its path towards being merged into cargo.

**Comment by nicoburns** [comment]
Closing this now. Any additional suggestions can be submitted via a new issue :)
