### ISSUE TITLE
Add polars library for processing dataframes

### ISSUE THREAD

**Issue by varunmehrishi** [nicoburns/blessed-rs#48]
[Polars ](https://github.com/pola-rs/polars) is a dataframe library written in Rust.
It is similar to pandas library in Python and is highly performant as per [benchmarks](https://h2oai.github.io/db-benchmark/).

**Comment by nicoburns** [comment]
Agreed that this should be on the list. I am planning on adding a "Math / Scientific" category which I believe polars would fit into nicely.
