### ISSUE TITLE
Question: something similar for Go?

### ISSUE THREAD

**Issue by jabbalaci** [nicoburns/blessed-rs#60]
This is a great list. I just wonder: is there something similar for Go? My problem is the same: I have no idea which package to pick. Thanks in advance.

**Comment by nicoburns** [comment]
Hi there. Unfortunately I don't know much about the Go ecosystem. Maybe try asking on https://www.reddit.com/r/golang/ ?

**Comment by jabbalaci** [comment]
Thanks. I posed the question: https://old.reddit.com/r/golang/comments/100i8x6/is_there_something_similar_to_blessedrs/ . Let's see how they react.
