### ISSUE TITLE
Druid is being discontinued

### ISSUE THREAD

**Issue by jtdowney** [nicoburns/blessed-rs#69]
I noticed the druid repo now contains a [discontinuation notice](https://github.com/linebender/druid#project-status), and it points to https://github.com/linebender/xilem as the successor.

**Comment by nicoburns** [comment]
Indeed it is. I've actually been looking into the state of Rust GUI recently, and I have a guide/overview of both high-level frameworks and the lower-level building blocks in the works :)

**Comment by nicoburns** [comment]
I've moved Druid out of the "recommended" section and into the "see also" section (I've also filled out the GUI section with a lot more libraries).
