### ISSUE TITLE
Adding ratatui ?

### ISSUE THREAD

**Issue by mindoodoo** [nicoburns/blessed-rs#72]
It was recently mentioned [here](https://github.com/tui-rs-revival/ratatui/issues/89) that we should consider adding [ratatui](https://github.com/tui-rs-revival/ratatui) to blessed.rs. I hadn't heard of blessed.rs before so I am unfamiliar with the process for adding a project to it.

The ratatui fork was recently created as the original maintainer of the [tui](https://github.com/fdehau/tui-rs) crate was no longer responding. The crate is being actively maintained and we are about to release the first version of the crate since the fork.

**Comment by nicoburns** [comment]
Happy to add `ratatui`. However, I'd like to wait until it's been released to crates.io and is available to users.

**Comment by mindoodoo** [comment]
Sounds good, first release should be this sunday

**Comment by mindoodoo** [comment]
Thank you ! :)
