### ISSUE TITLE
once_cell has been merged into std and stabilized

### ISSUE THREAD

**Issue by wathenjiang** [nicoburns/blessed-rs#84]
Hey, I found out `once_cell` has been merged into `std` and stabilized, ref https://github.com/rust-lang/rust/pull/105587.

The description of once_cell : `Newer crate with more ergonomic API. On track to be incorporated into the standard library. Should be preferred for all new projects.` could be updated.

**Comment by epage** [comment]
Only a subset of `once_cell` has been merged *but* for a lot of lower level crates, that subset should be sufficient
