### ISSUE TITLE
Consider adding inquire

### ISSUE THREAD

**Issue by senekor** [nicoburns/blessed-rs#98]
I recently discovered [`inquire`](https://docs.rs/inquire/latest/inquire/), which is just what I needed at the time. It was one of those "I wish someone (like blessed.rs) had told me about this sooner!"

That being said, I haven't put much more thought into whether it's a good fit for the site beyond that it seems high quality and useful for a broad range of use cases. I'm guessing there's more that goes into the descision? Popularity, maintenance status...

I'd say [CLIs > Terminal Rendering](https://blessed.rs/crates#section-cli-tools-subsection-rendering) would be an appropriate place.

Thanks for considering it.

**Comment by djc** [comment]
At 300k recent downloads, seems like it's sufficient popular -- seems reasonable to include it.
